version: 0.2

env:
  variables:
    key: "value"

phases:
  install:
    commands:
      - echo Entered the install phase...
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - go test
    finally:
      - echo This always runs even if the login command fails 
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - GOOS=linux GOARCH=arm64 go build -o app-linux-arm64
      - GOOS=darwin GOARCH=arm64 go build -o app-darwin-arm64
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - app-linux-arm64
    - app-darwin-arm64
  discard-paths: yes

